development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: sosdenuncia_development
  pool: 5
  username: root
  password:
  #socket: /opt/local/var/run/mysql5/mysqld.sock
test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: sosdenuncia_test
  pool: 5
  username: root
  password:
  #socket: /opt/local/var/run/mysql5/mysqld.sock

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: sosdenuncia_production
  pool: 5
  username: root
  password:
  #socket: /opt/local/var/run/mysql5/mysqld.sock
