development:
  adapter: postgresql
  encoding: unicode
  database: sos_denuncia_development
  pool: 5
  timeout: 5000
  username: gpereir
  password:

test:
  adapter: postgresql
  database: sos_denuncia_test
  pool: 5
  timeout: 5000
  username: gpereir
  password:
